import {
  Button,
  Stack,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableRow,
  TableSortLabel,
  TextField,
  Typography,
} from "@mui/material";
import { useState } from "react";

function PriceChart({ entries }) {
  // entries[0] - title, entries[1] - number, entries[2] - price range
  return (
    <div>
      <Table>
        <TableHead>
          <TableRow>
            <TableCell>Title</TableCell>
            <TableCell>Issue Number</TableCell>
            <TableCell>
              <TableSortLabel active={true}></TableSortLabel>
              Est. Price Range
            </TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {entries.map((value, i) => {
            return (
              <TableRow key={i}>
                <TableCell>{value[0]}</TableCell>
                <TableCell>{value[1]}</TableCell>
                <TableCell>
                  <strong>{value[2]}</strong>
                </TableCell>
              </TableRow>
            );
          })}
        </TableBody>
      </Table>
    </div>
  );
}

export default function ComicPricing() {
  const [pastedCSV, setPastedCSV] = useState("");
  const [entries, setEntries] = useState([]);

  const onSubmit = async () => {
    console.log(pastedCSV);
    const comics = pastedCSV.split(",");
    const response = await fetch("/api/price_response", {
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
      },
      method: "POST",
      body: JSON.stringify(comics),
    });
    const data = await response.json();
    console.log(data);
    setEntries(data.message);
  };

  return (
    <Stack direction="row" spacing={2} sx={{ justifyContent: "space-evenly" }}>
      <Stack
        direction="column"
        spacing={2}
        sx={{ justifyContent: "space-evenly" }}
      >
        <Typography>
          Please paste your CSV of comics you would like to approximate the
          value of below
        </Typography>
        <Typography>
          **Disclaimer: These are generated by AI and thus may not be accurate!
        </Typography>
        <Typography>
          Please follow the format of: <i>Name Number, Name Number </i> - no #
          signs please!
        </Typography>
        <TextField
          name="prompt"
          label=""
          rows="25"
          cols="15"
          multiline={true}
          onChange={(event) => {
            setPastedCSV(event.target.value);
          }}
        />
        <Button variant="outlined" type="submit" onClick={onSubmit}>
          Submit Answers
        </Button>
      </Stack>
      <PriceChart entries={entries} />
    </Stack>
  );
}
